name: 'Push to Docker'

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Generate sha'
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build Docker image'
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t am4r0/mysite:${{ steps.generate_sha.outputs.sha }} .
          docker buildx build --platform linux/arm64 -t am4r0/mysite:latest .

      - name: 'Push image'
        run: |
          docker buildx build --platform linux/arm64 --push -t am4r0/mysite:${{ steps.generate_sha.outputs.sha }} .
          docker buildx build --platform linux/arm64 --push -t am4r0/mysite:latest .
